# Generated by Django 5.2.9 on 2026-05-24 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="repertoirepage",
            name="ordre_important",
            field=models.BooleanField(
                default=False,
                help_text="Si coché, les morceaux sont numérotés (#1, #2, …) dans l'ordre du répertoire.",
                verbose_name="Ordre important",
            ),
        ),
        migrations.AlterField(
            model_name="piece",
            name="timecodes",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Texte libre. Insérez des timecodes au format [mm:ss] dans les paroles ; ils seront convertis en boutons cliquables dans le lecteur. Exemple : [00:10]Ave Maria, gratia plena\\nDominus tecum, [00:20]Ave Maria",
                verbose_name="Paroles avec timecodes",
            ),
            preserve_default=False,
        ),
        # Les anciennes lignes contiennent du JSON StreamField stocké en TEXT.
        # On les vide : le format est incompatible avec le nouveau champ « paroles + [mm:ss] ».
        migrations.RunSQL(
            sql="UPDATE music_piece SET timecodes = '';",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
