# Generated by Django 5.2.9 on 2026-05-23 11:12

from django.db import migrations, models
from django.utils.text import slugify


def generate_slugs(apps, schema_editor):
    Piece = apps.get_model("music", "Piece")
    for piece in Piece.objects.all():
        base = slugify(piece.titre) or f"piece-{piece.pk}"
        slug = base
        n = 1
        while Piece.objects.filter(slug=slug).exclude(pk=piece.pk).exists():
            slug = f"{base}-{n}"
            n += 1
        piece.slug = slug
        piece.save(update_fields=["slug"])


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="piece",
            name="slug",
            field=models.SlugField(blank=True, max_length=250),
        ),
        migrations.RunPython(generate_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="piece",
            name="slug",
            field=models.SlugField(blank=True, max_length=250, unique=True),
        ),
    ]
