# Generated by Django 5.2.9 on 2026-05-23 11:32

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0003_remove_repertoireitem_icon_piecetag_piece_tags"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="piece",
            name="tags",
        ),
        migrations.AddField(
            model_name="repertoireitem",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.DeleteModel(
            name="PieceTag",
        ),
    ]
