# Generated by Django 5.2.9 on 2026-05-23 10:48

import datetime
import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "verbose_name": "Page de contenu",
                "verbose_name_plural": "Pages de contenu",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("name", models.TextField(help_text="Site title")),
                ("header", models.TextField(help_text="Header")),
                ("body", wagtail.fields.RichTextField(help_text="Page content")),
            ],
            options={
                "verbose_name": "Page d'accueil",
                "verbose_name_plural": "Pages d'accueil",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="ContentSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Titre")),
                (
                    "date",
                    models.DateField(default=datetime.date.today, verbose_name="Date"),
                ),
                ("body", wagtail.fields.RichTextField(verbose_name="Contenu")),
                (
                    "references",
                    wagtail.fields.StreamField(
                        [("event", 3), ("piece", 4)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.snippets.blocks.SnippetChooserBlock",
                                ("community.Event",),
                                {"label": "Événement"},
                            ),
                            1: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {"label": "Contenu supplémentaire", "required": False},
                            ),
                            2: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("minified", "Version réduite"),
                                        ("modal", "Modale"),
                                    ],
                                    "label": "Affichage",
                                },
                            ),
                            3: (
                                "wagtail.blocks.StructBlock",
                                [[("event", 0), ("extra_content", 1), ("display", 2)]],
                                {},
                            ),
                            4: (
                                "wagtail.snippets.blocks.SnippetChooserBlock",
                                ("music.Piece",),
                                {},
                            ),
                        },
                        null=True,
                        verbose_name="Références",
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="content.contentpage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
