# Generated by Django 5.2.9 on 2026-05-23 11:04

import wagtail.fields
from django.db import migrations


def clear_body(apps, schema_editor):
    ContentSection = apps.get_model("content", "ContentSection")
    ContentSection.objects.update(body="[]")


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(clear_body, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="contentsection",
            name="references",
        ),
        migrations.AlterField(
            model_name="contentsection",
            name="body",
            field=wagtail.fields.StreamField(
                [("text", 0), ("event", 3), ("piece", 4)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.RichTextBlock", (), {"label": "Texte"}),
                    1: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("community.Event",),
                        {"label": "Événement"},
                    ),
                    2: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"label": "Contenu supplémentaire", "required": False},
                    ),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("event", 1), ("extra_content", 2)]],
                        {},
                    ),
                    4: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("music.Piece",),
                        {"label": "Morceau"},
                    ),
                },
                verbose_name="Contenu",
            ),
        ),
    ]
