# Generated by Django 5.2.9 on 2026-05-23 11:32

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_remove_contentsection_references_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentsection",
            name="body",
            field=wagtail.fields.RichTextField(verbose_name="Contenu"),
        ),
    ]
