# Generated by Django 5.2.9 on 2026-05-23 11:38

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0003_alter_contentsection_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentsection",
            name="references",
            field=wagtail.fields.StreamField(
                [("event", 2), ("piece", 3)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("community.Event",),
                        {"label": "Événement"},
                    ),
                    1: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"label": "Contenu supplémentaire", "required": False},
                    ),
                    2: (
                        "wagtail.blocks.StructBlock",
                        [[("event", 0), ("extra_content", 1)]],
                        {},
                    ),
                    3: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("music.Piece",),
                        {},
                    ),
                },
                null=True,
                verbose_name="Références",
            ),
        ),
        migrations.AlterField(
            model_name="contentsection",
            name="body",
            field=wagtail.fields.RichTextField(blank=True, verbose_name="Contenu"),
        ),
    ]
