# Generated by Django 5.2.9 on 2026-05-23 11:39

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0004_contentsection_references_alter_contentsection_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentsection",
            name="references",
            field=wagtail.fields.StreamField(
                [("event", 2), ("piece", 3)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("community.Event",),
                        {"label": "Événement"},
                    ),
                    1: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"label": "Contenu supplémentaire", "required": False},
                    ),
                    2: (
                        "wagtail.blocks.StructBlock",
                        [[("event", 0), ("extra_content", 1)]],
                        {},
                    ),
                    3: ("apps.content.blocks.PieceBlock", (), {}),
                },
                null=True,
                verbose_name="Références",
            ),
        ),
    ]
