# Generated by Django 5.2.9 on 2026-05-23 10:48

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
import wagtail_color_panel.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="NavigationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(
                        blank=True,
                        help_text="Affiché à côté du logo ou seul si pas de logo",
                        max_length=100,
                        verbose_name="Nom du site",
                    ),
                ),
                (
                    "logo",
                    models.ForeignKey(
                        blank=True,
                        help_text="Logo affiché dans la navbar (recommandé : 150x50px)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Logo",
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Navigation",
                "verbose_name_plural": "Navigation",
            },
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                ("title", models.CharField(max_length=50, verbose_name="Titre")),
                ("link_url", models.URLField(blank=True, verbose_name="URL externe")),
                (
                    "open_in_new_tab",
                    models.BooleanField(
                        default=False, verbose_name="Ouvrir dans un nouvel onglet"
                    ),
                ),
                (
                    "icon_class",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Classe d'icône"
                    ),
                ),
                (
                    "show_on_mobile",
                    models.BooleanField(
                        default=True, verbose_name="Afficher sur mobile"
                    ),
                ),
                (
                    "link_page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.page",
                        verbose_name="Page interne",
                    ),
                ),
                (
                    "navigation",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menu_items",
                        to="core.navigationsettings",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SecuritySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Mot de passe pour protéger l'accès au site",
                        max_length=128,
                        verbose_name="Mot de passe",
                    ),
                ),
                (
                    "login_message",
                    wagtail.fields.RichTextField(
                        blank=True,
                        default="",
                        help_text="Message affiché sur la page de connexion",
                        verbose_name="Message d'accueil",
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sécurité",
                "verbose_name_plural": "Sécurité",
            },
        ),
        migrations.CreateModel(
            name="ThemeSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "primary_color",
                    wagtail_color_panel.fields.ColorField(
                        default="#8a4d76",
                        help_text="Boutons, liens, accents principaux",
                        max_length=7,
                    ),
                ),
                (
                    "secondary_color",
                    wagtail_color_panel.fields.ColorField(
                        default="#fa7c91",
                        help_text="Survols, éléments secondaires",
                        max_length=7,
                    ),
                ),
                (
                    "tertiary_color",
                    wagtail_color_panel.fields.ColorField(
                        default="#3e8ed0",
                        help_text="Badges, tags, informations",
                        max_length=7,
                    ),
                ),
                (
                    "background_color",
                    wagtail_color_panel.fields.ColorField(
                        default="#f5f5f5", help_text="Fond de page", max_length=7
                    ),
                ),
                (
                    "text_color",
                    wagtail_color_panel.fields.ColorField(
                        default="#2c3e50", help_text="Texte principal", max_length=7
                    ),
                ),
                (
                    "text_muted_color",
                    wagtail_color_panel.fields.ColorField(
                        default="#95a5a6", help_text="Texte secondaire", max_length=7
                    ),
                ),
                (
                    "navbar_bg",
                    wagtail_color_panel.fields.ColorField(
                        default="#8a4d76",
                        help_text="Fond de la navigation",
                        max_length=7,
                    ),
                ),
                (
                    "navbar_text",
                    wagtail_color_panel.fields.ColorField(
                        default="#ffffff", help_text="Texte de navigation", max_length=7
                    ),
                ),
                (
                    "navbar_hover_bg",
                    wagtail_color_panel.fields.ColorField(
                        default="#6b3a5d", help_text="Fond au survol", max_length=7
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Thème",
                "verbose_name_plural": "Thème",
            },
        ),
    ]
