# Generated by Django 5.1.5 on 2025-05-12 18:37

import django.db.models.deletion
import wagtail.fields
import wagtail_color_panel.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentpage",
            name="content",
            field=wagtail.fields.StreamField(
                [("contenu", 0), ("image", 4), ("colonnes", 12)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.RichTextBlock", (), {}),
                    1: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": True},
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Ajouter une légende", "required": False},
                    ),
                    3: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("160", "Petit"),
                                ("320", "Moyen"),
                                ("640", "Grand"),
                                ("full", "Max"),
                            ],
                            "help_text": "Sélectionnez la taille de l'image",
                        },
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 1), ("caption", 2), ("width", 3)]],
                        {},
                    ),
                    5: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    6: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("internal", "Page interne"),
                                ("external", "URL externe"),
                            ],
                            "icon": "link",
                        },
                    ),
                    7: ("wagtail.blocks.PageChooserBlock", (), {"required": False}),
                    8: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    9: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("link_type", 6),
                                ("internal_page", 7),
                                ("external_url", 8),
                                ("link_text", 9),
                            ]
                        ],
                        {"required": False},
                    ),
                    11: (
                        "wagtail.blocks.StreamBlock",
                        [[("content", 5), ("button", 10)]],
                        {},
                    ),
                    12: ("wagtail.blocks.StreamBlock", [[("columns", 11)]], {}),
                },
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="StyleSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "primary_color",
                    wagtail_color_panel.fields.ColorField(
                        default="#FF0000", max_length=7
                    ),
                ),
                (
                    "secondary_color",
                    wagtail_color_panel.fields.ColorField(
                        default="#FF0000", max_length=7
                    ),
                ),
                (
                    "third_color",
                    wagtail_color_panel.fields.ColorField(
                        default="#FF0000", max_length=7
                    ),
                ),
                ("generic_theme", models.BooleanField(default=False)),
                (
                    "password_message",
                    wagtail.fields.RichTextField(
                        default="",
                        help_text="Le texte qui sera affiché sur la page de demande de mot de passe.",
                    ),
                ),
                (
                    "image_password",
                    models.ForeignKey(
                        blank=True,
                        help_text="Image qui sera affichée sur la page de demande de mot de passe.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "logo",
                    models.ForeignKey(
                        blank=True,
                        help_text="Logo de votre site",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Customisation",
            },
        ),
    ]
