# Generated by Django 5.2.9 on 2026-01-04 10:23

import django.db.models.deletion
import wagtail.fields
import wagtail_color_panel.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contentpage",
            options={
                "verbose_name": "Content Page",
                "verbose_name_plural": "Content Pages",
            },
        ),
        migrations.AlterModelOptions(
            name="stylesettings",
            options={
                "verbose_name": "Style Settings",
                "verbose_name_plural": "Style Settings",
            },
        ),
        migrations.RemoveField(
            model_name="stylesettings",
            name="background_color",
        ),
        migrations.RemoveField(
            model_name="stylesettings",
            name="event_concert_color",
        ),
        migrations.RemoveField(
            model_name="stylesettings",
            name="event_rehearsal_color",
        ),
        migrations.RemoveField(
            model_name="stylesettings",
            name="image_password",
        ),
        migrations.RemoveField(
            model_name="stylesettings",
            name="navbar_bg",
        ),
        migrations.RemoveField(
            model_name="stylesettings",
            name="navbar_hover_bg",
        ),
        migrations.RemoveField(
            model_name="stylesettings",
            name="navbar_text",
        ),
        migrations.RemoveField(
            model_name="stylesettings",
            name="password_message",
        ),
        migrations.RemoveField(
            model_name="stylesettings",
            name="site_name",
        ),
        migrations.RemoveField(
            model_name="stylesettings",
            name="text_color",
        ),
        migrations.RemoveField(
            model_name="stylesettings",
            name="text_muted_color",
        ),
        migrations.RemoveField(
            model_name="stylesettings",
            name="title_h1_color",
        ),
        migrations.RemoveField(
            model_name="stylesettings",
            name="title_h2_color",
        ),
        migrations.RemoveField(
            model_name="stylesettings",
            name="title_h3_color",
        ),
        migrations.AddField(
            model_name="stylesettings",
            name="generic_theme",
            field=models.BooleanField(
                default=False,
                help_text="Enable generic theme for home page",
                verbose_name="Use generic theme",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.RichTextField(help_text="Page content"),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="header",
            field=models.TextField(help_text="Header"),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="name",
            field=models.TextField(help_text="Site title"),
        ),
        migrations.AlterField(
            model_name="stylesettings",
            name="block_header_bg",
            field=wagtail_color_panel.fields.ColorField(
                default="#8a4d76", help_text="Block header background", max_length=7
            ),
        ),
        migrations.AlterField(
            model_name="stylesettings",
            name="block_header_text",
            field=wagtail_color_panel.fields.ColorField(
                default="#ffffff", help_text="Block header text", max_length=7
            ),
        ),
        migrations.AlterField(
            model_name="stylesettings",
            name="logo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Logo",
            ),
        ),
        migrations.AlterField(
            model_name="stylesettings",
            name="primary_color",
            field=wagtail_color_panel.fields.ColorField(
                default="#8a4d76",
                help_text="Primary color - Buttons, links, main accents",
                max_length=7,
            ),
        ),
        migrations.AlterField(
            model_name="stylesettings",
            name="secondary_color",
            field=wagtail_color_panel.fields.ColorField(
                default="#fa7c91",
                help_text="Secondary color - Hovers, secondary elements",
                max_length=7,
            ),
        ),
        migrations.AlterField(
            model_name="stylesettings",
            name="tertiary_color",
            field=wagtail_color_panel.fields.ColorField(
                default="#3e8ed0",
                help_text="Tertiary color - Badges, tags, info",
                max_length=7,
            ),
        ),
        migrations.AlterModelOptions(
            name="stylesettings",
            options={
                "verbose_name": "Paramètres du site",
                "verbose_name_plural": "Paramètres du site",
            },
        ),
        migrations.RemoveField(
            model_name="stylesettings",
            name="block_header_bg",
        ),
        migrations.RemoveField(
            model_name="stylesettings",
            name="block_header_text",
        ),
        migrations.RemoveField(
            model_name="stylesettings",
            name="generic_theme",
        ),
        migrations.AddField(
            model_name="stylesettings",
            name="background_color",
            field=wagtail_color_panel.fields.ColorField(
                default="#f5f5f5", help_text="Fond de page", max_length=7
            ),
        ),
        migrations.AddField(
            model_name="stylesettings",
            name="login_message",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="",
                help_text="Message affiché sur la page de connexion",
                verbose_name="Message d'accueil",
            ),
        ),
        migrations.AddField(
            model_name="stylesettings",
            name="navbar_bg",
            field=wagtail_color_panel.fields.ColorField(
                default="#8a4d76", help_text="Fond de la navigation", max_length=7
            ),
        ),
        migrations.AddField(
            model_name="stylesettings",
            name="navbar_hover_bg",
            field=wagtail_color_panel.fields.ColorField(
                default="#6b3a5d", help_text="Fond au survol", max_length=7
            ),
        ),
        migrations.AddField(
            model_name="stylesettings",
            name="navbar_text",
            field=wagtail_color_panel.fields.ColorField(
                default="#ffffff", help_text="Texte de navigation", max_length=7
            ),
        ),
        migrations.AddField(
            model_name="stylesettings",
            name="password",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Mot de passe pour protéger l'accès au site",
                max_length=128,
                verbose_name="Mot de passe",
            ),
        ),
        migrations.AddField(
            model_name="stylesettings",
            name="text_color",
            field=wagtail_color_panel.fields.ColorField(
                default="#2c3e50", help_text="Texte principal", max_length=7
            ),
        ),
        migrations.AddField(
            model_name="stylesettings",
            name="text_muted_color",
            field=wagtail_color_panel.fields.ColorField(
                default="#95a5a6", help_text="Texte secondaire", max_length=7
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="icon_class",
            field=models.CharField(
                blank=True,
                help_text="Classe FontAwesome (ex: fas fa-home)",
                max_length=50,
                verbose_name="Classe d'icône",
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="link_page",
            field=models.ForeignKey(
                blank=True,
                help_text="Lien vers une page du site",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.page",
                verbose_name="Page interne",
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="link_url",
            field=models.CharField(
                blank=True,
                help_text="Ou lien vers une URL externe (si pas de page interne)",
                max_length=500,
                verbose_name="URL externe",
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="open_in_new_tab",
            field=models.BooleanField(
                default=False, verbose_name="Ouvrir dans un nouvel onglet"
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="show_on_mobile",
            field=models.BooleanField(default=True, verbose_name="Afficher sur mobile"),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="title",
            field=models.CharField(
                help_text="Texte affiché dans le menu",
                max_length=50,
                verbose_name="Titre",
            ),
        ),
        migrations.AlterField(
            model_name="stylesettings",
            name="logo",
            field=models.ForeignKey(
                blank=True,
                help_text="Logo du site affiché dans la navigation",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Logo",
            ),
        ),
        migrations.AlterField(
            model_name="stylesettings",
            name="primary_color",
            field=wagtail_color_panel.fields.ColorField(
                default="#8a4d76",
                help_text="Couleur principale - Boutons, liens, accents principaux",
                max_length=7,
            ),
        ),
        migrations.AlterField(
            model_name="stylesettings",
            name="secondary_color",
            field=wagtail_color_panel.fields.ColorField(
                default="#fa7c91",
                help_text="Couleur secondaire - Survols, éléments secondaires",
                max_length=7,
            ),
        ),
        migrations.AlterField(
            model_name="stylesettings",
            name="tertiary_color",
            field=wagtail_color_panel.fields.ColorField(
                default="#3e8ed0",
                help_text="Couleur tertiaire - Badges, tags, informations",
                max_length=7,
            ),
        ),
        migrations.AlterField(
            model_name="contentpage",
            name="content",
            field=wagtail.fields.StreamField(
                [("section", 27)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional title displayed above the section",
                            "label": "Section title",
                            "required": False,
                        },
                    ),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("1", "Full width"),
                                ("1-1", "Two columns (1/2 + 1/2)"),
                                ("1-2", "Two columns (1/3 + 2/3)"),
                                ("2-1", "Two columns (2/3 + 1/3)"),
                                ("1-1-1", "Three columns (equal)"),
                            ],
                            "label": "Layout",
                        },
                    ),
                    2: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("left", "Left"),
                                ("center", "Center"),
                                ("right", "Right"),
                            ],
                            "label": "Alignment",
                        },
                    ),
                    3: ("wagtail.blocks.RichTextBlock", (), {"label": "Rich Text"}),
                    4: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("internal", "Page interne"),
                                ("external", "URL externe"),
                            ],
                            "icon": "link",
                            "label": "Type de lien",
                        },
                    ),
                    5: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"label": "Page interne", "required": False},
                    ),
                    6: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"label": "URL externe", "required": False},
                    ),
                    7: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Texte du bouton", "required": True},
                    ),
                    8: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("is-primary", "Principal"),
                                ("is-secondary", "Secondaire"),
                                ("is-outlined is-primary", "Contour"),
                            ],
                            "label": "Style",
                        },
                    ),
                    9: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "label": "Ouvrir dans un nouvel onglet",
                            "required": False,
                        },
                    ),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("link_type", 4),
                                ("internal_page", 5),
                                ("external_url", 6),
                                ("link_text", 7),
                                ("style", 8),
                                ("open_in_new_tab", 9),
                            ]
                        ],
                        {},
                    ),
                    11: ("wagtail.contrib.table_block.blocks.TableBlock", (), {}),
                    12: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "label": "First row is header",
                            "required": False,
                        },
                    ),
                    13: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "label": "First column is header",
                            "required": False,
                        },
                    ),
                    14: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("simple", "Simple"),
                                ("striped", "Striped"),
                                ("bordered", "Bordered"),
                            ],
                            "label": "Style",
                        },
                    ),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("table", 11),
                                ("first_row_is_header", 12),
                                ("first_col_is_header", 13),
                                ("style", 14),
                            ]
                        ],
                        {},
                    ),
                    16: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("blue", "Blue"),
                                ("green", "Green"),
                                ("yellow", "Yellow"),
                                ("red", "Red"),
                            ],
                            "label": "Color",
                        },
                    ),
                    17: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional title for the alert",
                            "label": "Title",
                            "required": False,
                        },
                    ),
                    18: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"features": ["bold", "italic", "link"], "label": "Content"},
                    ),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [[("color", 16), ("title", 17), ("content", 18)]],
                        {},
                    ),
                    20: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("choristes.Evenement",),
                        {"label": "Event"},
                    ),
                    21: ("wagtail.blocks.StructBlock", [[("event", 20)]], {}),
                    22: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("content", 3),
                                ("button", 10),
                                ("table", 15),
                                ("alert", 19),
                                ("event", 21),
                            ]
                        ],
                        {"label": "Content"},
                    ),
                    23: (
                        "wagtail.blocks.StructBlock",
                        [[("alignment", 2), ("content", 22)]],
                        {},
                    ),
                    24: (
                        "wagtail.blocks.ListBlock",
                        (23,),
                        {"collapsed": True, "label": "Columns"},
                    ),
                    25: (
                        "wagtail.blocks.StructBlock",
                        [[("layout", 1), ("columns", 24)]],
                        {},
                    ),
                    26: (
                        "wagtail.blocks.ListBlock",
                        (25,),
                        {"collapsed": True, "label": "Rows"},
                    ),
                    27: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("rows", 26)]],
                        {},
                    ),
                },
                null=True,
            ),
        ),
    ]
