# Generated by Django 4.2.10 on 2024-05-13 09:36

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
import wagtail_color_panel.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentpage',
            name='content',
            field=wagtail.fields.StreamField([('contenu', wagtail.blocks.RichTextBlock()), ('image', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('caption', wagtail.blocks.CharBlock(help_text='Ajouter une légende', required=False)), ('width', wagtail.blocks.ChoiceBlock(choices=[('160', 'Petit'), ('320', 'Moyen'), ('640', 'Grand'), ('full', 'Max')], help_text="Sélectionnez la taille de l'image"))])), ('colonnes', wagtail.blocks.StreamBlock([('columns', wagtail.blocks.StreamBlock([('content', wagtail.blocks.RichTextBlock(required=False)), ('button', wagtail.blocks.StructBlock([('link_type', wagtail.blocks.ChoiceBlock(choices=[('internal', 'Page interne'), ('external', 'URL externe')], icon='link')), ('internal_page', wagtail.blocks.PageChooserBlock(required=False)), ('external_url', wagtail.blocks.URLBlock(required=False)), ('link_text', wagtail.blocks.CharBlock(required=True))], required=False))]))]))], blank=True, null=True, use_json_field=True),
        ),
        migrations.CreateModel(
            name='StyleSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', wagtail_color_panel.fields.ColorField(default='#FF0000', max_length=7)),
                ('secondary_color', wagtail_color_panel.fields.ColorField(default='#FF0000', max_length=7)),
                ('third_color', wagtail_color_panel.fields.ColorField(default='#FF0000', max_length=7)),
                ('generic_theme', models.BooleanField(default=False)),
                ('password_message', wagtail.fields.RichTextField(default='', help_text='Le texte qui sera affiché sur la page de demande de mot de passe.')),
                ('image_password', models.ForeignKey(blank=True, help_text='Image qui sera affichée sur la page de demande de mot de passe.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('logo', models.ForeignKey(blank=True, help_text='Logo de votre site', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Customisation',
            },
        ),
    ]
