# Generated by Django 4.2.7 on 2023-11-20 14:47

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.RichTextField(default='dfj', help_text='Contenu de la page'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='header',
            field=models.TextField(default='hedh', help_text='En-tête'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='name',
            field=models.TextField(default='jkdfj', help_text='Titre du site'),
            preserve_default=False,
        ),
    ]
