# Generated by Django 5.2.9 on 2025-12-26 09:47

import wagtail_color_panel.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_alter_contentpage_content_stylesettings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stylesettings",
            name="third_color",
        ),
        migrations.AddField(
            model_name="stylesettings",
            name="background_color",
            field=wagtail_color_panel.fields.ColorField(
                default="#f5f5f5", help_text="Couleur de fond de page", max_length=7
            ),
        ),
        migrations.AddField(
            model_name="stylesettings",
            name="block_header_bg",
            field=wagtail_color_panel.fields.ColorField(
                default="#8a4d76", help_text="Fond des en-têtes de blocs", max_length=7
            ),
        ),
        migrations.AddField(
            model_name="stylesettings",
            name="block_header_text",
            field=wagtail_color_panel.fields.ColorField(
                default="#ffffff", help_text="Texte des en-têtes de blocs", max_length=7
            ),
        ),
        migrations.AddField(
            model_name="stylesettings",
            name="tertiary_color",
            field=wagtail_color_panel.fields.ColorField(
                default="#3e8ed0", help_text="Couleur tertiaire", max_length=7
            ),
        ),
        migrations.AlterField(
            model_name="stylesettings",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="stylesettings",
            name="primary_color",
            field=wagtail_color_panel.fields.ColorField(
                default="#8a4d76", help_text="Couleur principale", max_length=7
            ),
        ),
        migrations.AlterField(
            model_name="stylesettings",
            name="secondary_color",
            field=wagtail_color_panel.fields.ColorField(
                default="#fa7c91", help_text="Couleur secondaire", max_length=7
            ),
        ),
    ]
