# Generated by Django 5.2.9 on 2025-12-26 09:56

import wagtail_color_panel.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_remove_stylesettings_third_color_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stylesettings",
            options={
                "verbose_name": "Customisation du Site",
                "verbose_name_plural": "Customisation du Site",
            },
        ),
        migrations.AddField(
            model_name="stylesettings",
            name="event_concert_color",
            field=wagtail_color_panel.fields.ColorField(
                default="#fa7c91",
                help_text="🎪 Concerts - Couleur pour les événements de type concert",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="stylesettings",
            name="event_rehearsal_color",
            field=wagtail_color_panel.fields.ColorField(
                default="#3e8ed0",
                help_text="🎪 Répétitions - Couleur pour les événements de type répétition",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="stylesettings",
            name="navbar_bg",
            field=wagtail_color_panel.fields.ColorField(
                default="#8a4d76",
                help_text="🔗 Fond de la navigation - Barre de menu principale",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="stylesettings",
            name="navbar_hover_bg",
            field=wagtail_color_panel.fields.ColorField(
                default="#6b3a5d",
                help_text="🔗 Fond au survol - Couleur quand on survole un lien du menu",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="stylesettings",
            name="navbar_text",
            field=wagtail_color_panel.fields.ColorField(
                default="#ffffff",
                help_text="🔗 Texte de navigation - Liens du menu",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="stylesettings",
            name="text_color",
            field=wagtail_color_panel.fields.ColorField(
                default="#2c3e50",
                help_text="📄 Texte principal - Couleur du contenu textuel",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="stylesettings",
            name="text_muted_color",
            field=wagtail_color_panel.fields.ColorField(
                default="#95a5a6",
                help_text="📄 Texte secondaire - Texte grisé, moins important",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="stylesettings",
            name="title_h1_color",
            field=wagtail_color_panel.fields.ColorField(
                default="#2c3e50",
                help_text="🎯 Titres principaux (h1) - Titres de pages",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="stylesettings",
            name="title_h2_color",
            field=wagtail_color_panel.fields.ColorField(
                default="#34495e",
                help_text="🎯 Sous-titres (h2) - Titres de sections majeures",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="stylesettings",
            name="title_h3_color",
            field=wagtail_color_panel.fields.ColorField(
                default="#7f8c8d",
                help_text="🎯 Titres de sections (h3) - Sous-sections",
                max_length=7,
            ),
        ),
        migrations.AlterField(
            model_name="stylesettings",
            name="background_color",
            field=wagtail_color_panel.fields.ColorField(
                default="#f5f5f5",
                help_text="📄 Fond de page - Couleur de fond général du site",
                max_length=7,
            ),
        ),
        migrations.AlterField(
            model_name="stylesettings",
            name="block_header_bg",
            field=wagtail_color_panel.fields.ColorField(
                default="#8a4d76",
                help_text="📦 Fond des en-têtes de blocs - Sections colorées des cartes de contenu",
                max_length=7,
            ),
        ),
        migrations.AlterField(
            model_name="stylesettings",
            name="block_header_text",
            field=wagtail_color_panel.fields.ColorField(
                default="#ffffff",
                help_text="📦 Texte des en-têtes de blocs - Doit contraster avec le fond",
                max_length=7,
            ),
        ),
        migrations.AlterField(
            model_name="stylesettings",
            name="generic_theme",
            field=models.BooleanField(
                default=False, help_text="Utiliser le thème générique simple"
            ),
        ),
        migrations.AlterField(
            model_name="stylesettings",
            name="primary_color",
            field=wagtail_color_panel.fields.ColorField(
                default="#8a4d76",
                help_text="🎨 Couleur principale - Boutons, liens, accents principaux",
                max_length=7,
            ),
        ),
        migrations.AlterField(
            model_name="stylesettings",
            name="secondary_color",
            field=wagtail_color_panel.fields.ColorField(
                default="#fa7c91",
                help_text="🎨 Couleur secondaire - Survols, éléments secondaires",
                max_length=7,
            ),
        ),
        migrations.AlterField(
            model_name="stylesettings",
            name="tertiary_color",
            field=wagtail_color_panel.fields.ColorField(
                default="#3e8ed0",
                help_text="🎨 Couleur tertiaire - Badges, tags, informations",
                max_length=7,
            ),
        ),
    ]
