# Generated by Django 4.2.7 on 2023-11-20 21:17

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('home', '0003_homepage_body_homepage_header_homepage_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('content', wagtail.fields.StreamField([('bouton', wagtail.blocks.StructBlock([('button_text', wagtail.blocks.CharBlock(help_text='Entrer une valeur ici annule le champ ci-dessus.', required=False)), ('color', wagtail.blocks.ChoiceBlock(choices=['blue', 'red'], required=False))]))], blank=True, null=True, use_json_field=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
