# Generated by Django 4.2.7 on 2023-11-20 21:27

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_contentpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentpage',
            name='content',
            field=wagtail.fields.StreamField([('bouton', wagtail.blocks.StructBlock([('button_text', wagtail.blocks.CharBlock(help_text='Entrer une valeur ici annule le champ ci-dessus.', required=False)), ('color', wagtail.blocks.ChoiceBlock(choices=[('blue', 'Blue'), ('red', 'Red')], required=False))]))], blank=True, null=True, use_json_field=True),
        ),
    ]
