# Generated by Django 4.2.7 on 2023-11-28 22:30

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_contentpage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentpage',
            name='content',
            field=wagtail.fields.StreamField([('contenu', wagtail.blocks.RichTextBlock()), ('image', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('caption', wagtail.blocks.CharBlock(help_text='Ajouter une légende', required=False))])), ('colonnes', wagtail.blocks.StreamBlock([('columns', wagtail.blocks.StreamBlock([('content', wagtail.blocks.RichTextBlock(required=False))]))]))], blank=True, null=True, use_json_field=True),
        ),
    ]
