# Generated by Django 5.2.9 on 2026-05-23 10:48

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CalendrierPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "how_many_events",
                    models.IntegerField(
                        blank=True,
                        default=5,
                        help_text="Définir combien d'événements afficher dans la liste des prochains événements.",
                        null=True,
                    ),
                ),
                (
                    "show_calendar",
                    models.BooleanField(
                        default=True,
                        help_text="Est-ce que vous voulez que le widget calendrier s'affiche ?",
                    ),
                ),
                (
                    "comment",
                    wagtail.fields.RichTextField(
                        blank=True,
                        help_text="Un espace pour ajouter des commentaires : les changements récents, les prochaines dates...",
                    ),
                ),
            ],
            options={
                "verbose_name": "Calendrier",
                "verbose_name_plural": "Calendriers",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="Choriste",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=False, verbose_name="Actif")),
                (
                    "name",
                    models.CharField(
                        help_text="Nom du choriste", max_length=255, verbose_name="Nom"
                    ),
                ),
                (
                    "pupitre",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Tutti", "Tutti"),
                            ("Soprano", "Soprano"),
                            ("Alto", "Alto"),
                            ("Mezzo-alto", "Mezzo-alto"),
                            ("Mezzo-soprano", "Mezzo-soprano"),
                            ("Ténor", "Ténor"),
                            ("Basse", "Basse"),
                            ("Autre", "Autre"),
                        ],
                        max_length=25,
                        null=True,
                        verbose_name="Pupitre",
                    ),
                ),
                (
                    "mail",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=15, null=True, verbose_name="Téléphone"
                    ),
                ),
                (
                    "birthdate",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de naissance"
                    ),
                ),
            ],
            options={
                "verbose_name": "Choriste",
                "verbose_name_plural": "Choristes",
            },
        ),
        migrations.CreateModel(
            name="ChoristesIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "verbose_name": "Page choristes",
                "verbose_name_plural": "Pages choristes",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Nom de l'événement"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "is_repetition",
                    models.BooleanField(default=True, verbose_name="Répétition"),
                ),
                (
                    "pupitre",
                    models.CharField(
                        choices=[
                            ("Tutti", "Tutti"),
                            ("Soprano", "Soprano"),
                            ("Alto", "Alto"),
                            ("Mezzo-alto", "Mezzo-alto"),
                            ("Mezzo-soprano", "Mezzo-soprano"),
                            ("Ténor", "Ténor"),
                            ("Basse", "Basse"),
                            ("Autre", "Autre"),
                        ],
                        max_length=25,
                        verbose_name="Pupitre",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        help_text="Date de début de l'événement (obligatoire)",
                        verbose_name="Date de début",
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Date de fin (si différente de la date de début)",
                        null=True,
                        verbose_name="Date de fin",
                    ),
                ),
                (
                    "time_tbd",
                    models.BooleanField(
                        default=False,
                        help_text="Cochez si l'heure n'est pas encore fixée",
                        verbose_name="Heure à déterminer",
                    ),
                ),
                (
                    "start_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Heure de début"
                    ),
                ),
                (
                    "end_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Heure de fin"
                    ),
                ),
                (
                    "lieu",
                    models.CharField(
                        blank=True, max_length=250, null=True, verbose_name="Lieu"
                    ),
                ),
                (
                    "adresse",
                    models.CharField(
                        blank=True, max_length=250, null=True, verbose_name="Adresse"
                    ),
                ),
            ],
            options={
                "verbose_name": "Événement",
                "verbose_name_plural": "Événements",
                "ordering": ["start_date", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nom de la fonction",
                        max_length=255,
                        verbose_name="Nom",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
            ],
            options={
                "verbose_name": "Fonction",
                "verbose_name_plural": "Fonctions",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                ("street", models.CharField(max_length=255, verbose_name="Rue")),
                (
                    "zip_code",
                    models.CharField(max_length=10, verbose_name="Code postal"),
                ),
                ("city", models.CharField(max_length=255, verbose_name="Localité")),
                (
                    "choriste",
                    modelcluster.fields.ParentalKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to="community.choriste",
                        verbose_name="Choriste",
                    ),
                ),
            ],
            options={
                "verbose_name": "Adresse",
                "verbose_name_plural": "Adresses",
            },
        ),
        migrations.AddField(
            model_name="choriste",
            name="choir_functions",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True,
                help_text="Fonctions dans le chœur",
                related_name="choristes",
                to="community.role",
                verbose_name="Fonctions",
            ),
        ),
    ]
