# Generated by Django 4.2.7 on 2023-11-04 11:32

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.documents.blocks
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoristesIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ChoristesPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('date', models.DateField(verbose_name='Post date')),
                ('intro', models.CharField(max_length=250)),
                ('body', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='MorceauIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('introduction', models.TextField(blank=True, help_text='Text to describe the page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='MorceauPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('titre_document', wagtail.blocks.StructBlock([('titre', wagtail.blocks.CharBlock(help_text='Entrez le titre', max_length=255, required=True)), ('texte', wagtail.blocks.TextBlock(help_text='Entrez le texte principal', required=True)), ('document_pdf', wagtail.documents.blocks.DocumentChooserBlock(help_text='Sélectionnez un document PDF', required=True)), ('documents_audio', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('audio', wagtail.documents.blocks.DocumentChooserBlock(help_text='Sélectionnez un fichier audio', required=False))]), help_text='Ajoutez entre 1 et 4 fichiers audio', max_num=4, min_num=0)), ('champs_texte_supplementaires', wagtail.blocks.StreamBlock([('texte_supplementaire', wagtail.blocks.TextBlock())], help_text='Ajoutez un nombre indéterminé de champs texte', required=False))]))], blank=True, null=True, use_json_field=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
