# Generated by Django 4.2.10 on 2024-04-14 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('choristes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evenement',
            old_name='repetition',
            new_name='is_repetition',
        ),
        migrations.AlterField(
            model_name='calendrierpage',
            name='calendrier_image',
            field=models.ForeignKey(blank=True, help_text='Le calendrier en format image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='choriste',
            name='mail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='choriste',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='choriste',
            name='pupitre',
            field=models.CharField(blank=True, choices=[('Tutti', 'Tutti'), ('Soprano', 'Soprano'), ('Alto', 'Alto'), ('Ténor', 'Ténor'), ('Basse', 'Basse'), ('Autre', 'Autre')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
