# Generated by Django 4.2.7 on 2023-11-05 08:16

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.documents.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0012_uploadeddocument'),
        ('choristes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='morceaupage',
            name='body',
        ),
        migrations.AddField(
            model_name='morceaupage',
            name='audios',
            field=wagtail.fields.StreamField([('audios', wagtail.blocks.StructBlock([('audio', wagtail.documents.blocks.DocumentChooserBlock(help_text='Sélectionnez un fichier audio', required=False))]))], blank=True, null=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='morceaupage',
            name='compositeur',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='morceaupage',
            name='descr',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='title')), ('paragraph', wagtail.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())], null=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='morceaupage',
            name='pdf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document'),
        ),
        migrations.AddField(
            model_name='morceaupage',
            name='titre',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
