# Generated by Django 5.1.5 on 2025-08-30 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("choristes", "0002_rename_repetition_evenement_is_repetition_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="calendrierpage",
            name="how_many_events",
        ),
        migrations.AddField(
            model_name="calendrierpage",
            name="events_per_page",
            field=models.IntegerField(
                default=5,
                help_text="Nombre d'événements affichés lors de la navigation",
                verbose_name="Nombre d'événements par page",
            ),
        ),
        migrations.AlterField(
            model_name="calendrierpage",
            name="comment",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="calendrierpage",
            name="show_calendar",
            field=models.BooleanField(default=True),
        ),
    ]
