# Generated by Django 4.2.7 on 2023-11-06 23:05

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('choristes', '0002_remove_morceaupage_body_morceaupage_audios_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='morceaupage',
            name='descr',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
