# Generated by Django 4.2.10 on 2024-05-13 09:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choristes', '0002_rename_repetition_evenement_is_repetition_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendrierpage',
            name='calendrier_image',
        ),
        migrations.AddField(
            model_name='calendrierpage',
            name='how_many_events',
            field=models.IntegerField(blank=True, default=5, help_text="\n    Définir combien d'événements afficher dans la liste des prochains événements.", null=True),
        ),
        migrations.AddField(
            model_name='calendrierpage',
            name='show_calendar',
            field=models.BooleanField(default=True, help_text="\n    Est-ce que vous voulez que le widget calendrier s'affiche ? (max. 100)\n    ", validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='evenement',
            name='adresse',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='evenement',
            name='lieu',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
