# Generated by Django 4.2.11 on 2025-05-12 19:25

import django.core.validators
from django.db import migrations, models
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('choristes', '0003_remove_calendrierpage_calendrier_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='morceaupage',
            name='activer_timecodes',
            field=models.BooleanField(default=False, help_text='Cochez pour activer la fonctionnalité de timecodes', verbose_name='Activer les timecodes'),
        ),
        migrations.AddField(
            model_name='morceaupage',
            name='timecodes',
            field=wagtail.fields.StreamField([('timecode', wagtail.blocks.StructBlock([('timecode', wagtail.blocks.CharBlock(help_text='Format mm:ss, ex: 02:45', label='Timecode', validators=[django.core.validators.RegexValidator(message='Le format doit être mm:ss (ex: 02:45)', regex='^([0-5][0-9]):([0-5][0-9])$')])), ('texte', wagtail.blocks.TextBlock(label='Texte associé'))]))], blank=True, null=True, use_json_field=True, verbose_name='Timecodes avec annotations'),
        ),
    ]
