# Generated by Django 5.1.5 on 2025-11-23 18:13

import django.core.validators
import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("choristes", "0003_remove_calendrierpage_how_many_events_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChoirRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nom de la fonction",
                        max_length=255,
                        verbose_name="Nom",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
            ],
            options={
                "verbose_name": "Fonction",
                "verbose_name_plural": "Fonctions",
                "ordering": ["name"],
            },
        ),
        migrations.AlterModelOptions(
            name="choriste",
            options={"verbose_name": "Choriste", "verbose_name_plural": "Choristes"},
        ),
        migrations.RemoveField(
            model_name="calendrierpage",
            name="events_per_page",
        ),
        migrations.AddField(
            model_name="calendrierpage",
            name="how_many_events",
            field=models.IntegerField(
                blank=True,
                default=5,
                help_text="\n    Définir combien d'événements afficher dans la liste des prochains événements.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="choriste",
            name="active",
            field=models.BooleanField(default=False, verbose_name="Actif"),
        ),
        migrations.AddField(
            model_name="choriste",
            name="birthdate",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date de naissance"
            ),
        ),
        migrations.AlterField(
            model_name="calendrierpage",
            name="comment",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Un espace pour ajouter des commentaires : les changements récents, les prochaines dates...",
            ),
        ),
        migrations.AlterField(
            model_name="calendrierpage",
            name="show_calendar",
            field=models.BooleanField(
                default=True,
                help_text="\n    Est-ce que vous voulez que le widget calendrier s'affiche ? (max. 100)\n    ",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="choriste",
            name="mail",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Email"
            ),
        ),
        migrations.AlterField(
            model_name="choriste",
            name="name",
            field=models.CharField(
                help_text="Nom du choriste", max_length=255, verbose_name="Nom"
            ),
        ),
        migrations.AlterField(
            model_name="choriste",
            name="phone",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="Téléphone"
            ),
        ),
        migrations.AlterField(
            model_name="choriste",
            name="pupitre",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Tutti", "Tutti"),
                    ("Soprano", "Soprano"),
                    ("Alto", "Alto"),
                    ("Mezzo-alto", "Mezzo-alto"),
                    ("Mezzo-soprano", "Mezzo-soprano"),
                    ("Ténor", "Ténor"),
                    ("Basse", "Basse"),
                    ("Autre", "Autre"),
                ],
                max_length=25,
                null=True,
                verbose_name="Pupitre",
            ),
        ),
        migrations.AlterField(
            model_name="evenement",
            name="pupitre",
            field=models.CharField(
                choices=[
                    ("Tutti", "Tutti"),
                    ("Soprano", "Soprano"),
                    ("Alto", "Alto"),
                    ("Mezzo-alto", "Mezzo-alto"),
                    ("Mezzo-soprano", "Mezzo-soprano"),
                    ("Ténor", "Ténor"),
                    ("Basse", "Basse"),
                    ("Autre", "Autre"),
                ],
                max_length=25,
            ),
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "street",
                    models.CharField(
                        help_text="Rue", max_length=255, verbose_name="Rue"
                    ),
                ),
                (
                    "zip_code",
                    models.CharField(max_length=10, verbose_name="Code postal"),
                ),
                ("city", models.CharField(max_length=255, verbose_name="Localité")),
                (
                    "choriste",
                    modelcluster.fields.ParentalKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to="choristes.choriste",
                        verbose_name="Choriste",
                    ),
                ),
            ],
            options={
                "verbose_name": "Adresse",
                "verbose_name_plural": "Adresses",
            },
        ),
        migrations.AddField(
            model_name="choriste",
            name="choir_functions",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True,
                help_text="Fonctions dans le chœur",
                related_name="choristes",
                to="choristes.choirrole",
                verbose_name="Fonctions",
            ),
        ),
    ]
