# Generated by Django 4.2.7 on 2023-11-06 23:22

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('choristes', '0004_calendriereventpage_calendrierpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendriereventpage',
            name='body',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='calendriereventpage',
            name='date',
            field=models.DateField(default='2023-10-10', verbose_name='Post date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calendriereventpage',
            name='intro',
            field=models.CharField(default='lqskdjlk', max_length=250),
            preserve_default=False,
        ),
    ]
