# Generated by Django 4.2.7 on 2023-11-09 17:29

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('choristes', '0006_calendrierpubliceventpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='morceaupage',
            name='traduction',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
