# Generated by Django 5.2.9 on 2025-12-26 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("choristes", "0006_alter_evenement_fields"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="evenement",
            options={
                "ordering": ["start_date", "start_time"],
                "verbose_name": "Événement",
                "verbose_name_plural": "Événements",
            },
        ),
        migrations.AddField(
            model_name="evenement",
            name="end_time",
            field=models.TimeField(
                blank=True,
                help_text="Heure de fin (optionnel)",
                null=True,
                verbose_name="Heure de fin",
            ),
        ),
        migrations.AddField(
            model_name="evenement",
            name="start_time",
            field=models.TimeField(
                blank=True,
                help_text="Heure de début (laissez vide si heure à déterminer)",
                null=True,
                verbose_name="Heure de début",
            ),
        ),
        migrations.AddField(
            model_name="evenement",
            name="time_tbd",
            field=models.BooleanField(
                default=False,
                help_text="Cochez si l'heure n'est pas encore fixée",
                verbose_name="Heure à déterminer",
            ),
        ),
        migrations.AlterField(
            model_name="evenement",
            name="adresse",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="Adresse"
            ),
        ),
        migrations.AlterField(
            model_name="evenement",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="evenement",
            name="end_date",
            field=models.DateField(
                blank=True,
                help_text="Date de fin (si différente de la date de début)",
                null=True,
                verbose_name="Date de fin",
            ),
        ),
        migrations.AlterField(
            model_name="evenement",
            name="is_repetition",
            field=models.BooleanField(default=True, verbose_name="Répétition"),
        ),
        migrations.AlterField(
            model_name="evenement",
            name="lieu",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="Lieu"
            ),
        ),
        migrations.AlterField(
            model_name="evenement",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Nom de l'événement"),
        ),
        migrations.AlterField(
            model_name="evenement",
            name="pupitre",
            field=models.CharField(
                choices=[
                    ("Tutti", "Tutti"),
                    ("Soprano", "Soprano"),
                    ("Alto", "Alto"),
                    ("Mezzo-alto", "Mezzo-alto"),
                    ("Mezzo-soprano", "Mezzo-soprano"),
                    ("Ténor", "Ténor"),
                    ("Basse", "Basse"),
                    ("Autre", "Autre"),
                ],
                max_length=25,
                verbose_name="Pupitre",
            ),
        ),
        migrations.AlterField(
            model_name="evenement",
            name="start_date",
            field=models.DateField(
                help_text="Date de début de l'événement (obligatoire)",
                verbose_name="Date de début",
            ),
        ),
    ]
