# Generated by Django 4.2.7 on 2023-11-17 02:31

from django.db import migrations
import wagtail.blocks
import wagtail.documents.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('choristes', '0008_newspage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='morceaupage',
            name='audios',
            field=wagtail.fields.StreamField([('audios', wagtail.blocks.StructBlock([('pupitre', wagtail.blocks.ChoiceBlock(choices=[('tutti', 'Tutti'), ('soprano', 'Soprano'), ('alto', 'Alto'), ('tenor', 'Ténor'), ('bass', 'Basse')], required=False)), ('custom_pupitre', wagtail.blocks.CharBlock(help_text='Pupitre custom', required=False)), ('audio', wagtail.documents.blocks.DocumentChooserBlock(help_text='Sélectionnez un fichier audio', required=False)), ('comment', wagtail.blocks.CharBlock(help_text='Un petit mot ?', max_length=255, required=False))]))], blank=True, null=True, use_json_field=True),
        ),
    ]
