# Generated by Django 4.2.3 on 2023-11-17 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choristes', '0010_alter_morceaupage_audios'),
    ]

    operations = [
        migrations.RenameField(
            model_name='morceaupage',
            old_name='titre',
            new_name='_title',
        ),
    ]
