# Generated by Django 4.2.3 on 2023-11-17 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choristes', '0011_rename_titre_morceaupage__title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='morceaupage',
            old_name='_title',
            new_name='titre',
        ),
    ]
